### ISSUE TITLE
Follow me went perfectly! Even the breakout state and navigating back. But then amigo says it failed to follow.

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/action_server#43]
[ERROR] [1499529096.220605]: Received comm state RECALLING when in simple state DONE with SimpleActionClient in NS /amigo/head_ref/action_server
Updating navigation.
Checking end criteria
Operator is at 0.878484 meters distance
Checking if done following
Operator is standing still for 10.081893 seconds
I'm close enough to the operator and he's been standing there for long enough
Checking if we pass the start timeout
Passed

[INFO] [1499529097.087290]: 'Moving to the meeting point.'
[INFO] [1499529097.106849]: State machine starting in initial state 'START_ANALYSIS' with userdata: 
	[]
[INFO] [1499529097.185728]: State machine transitioning 'START_ANALYSIS':'done'-->'NAVIGATE'
[INFO] [1499529097.185951]: State machine starting in initial state 'GET_PLAN' with userdata: 
	[]
[INFO] [1499529097.312385]: 'I'm on my way!'
[INFO] [1499529097.367708]: State machine transitioning 'GET_PLAN':'goal_ok'-->'EXECUTE_PLAN'
[INFO] [1499529101.776381]: State machine transitioning 'EXECUTE_PLAN':'blocked'-->'PLAN_BLOCKED'
[INFO] [1499529101.776552]: Plan blocked
[ERROR] [1499529102.742214]: SimpleActionClient received DONE twice
[INFO] [1499529104.279682]: Plan free again
[INFO] [1499529104.280005]: State machine transitioning 'PLAN_BLOCKED':'free'-->'EXECUTE_PLAN'
[ERROR] [1499529104.300339]: Received comm state RECALLING when in simple state DONE with SimpleActionClient in NS /amigo/head_ref/action_server
[ERROR] [1499529109.343740]: SimpleActionClient received DONE twice
[INFO] [1499529110.491703]: State machine transitioning 'EXECUTE_PLAN':'blocked'-->'PLAN_BLOCKED'
[INFO] [1499529110.491922]: Plan blocked
[INFO] [1499529110.992817]: Plan free again
[INFO] [1499529110.992997]: State machine transitioning 'PLAN_BLOCKED':'free'-->'EXECUTE_PLAN'
[ERROR] [1499529111.022958]: Received comm state RECALLING when in simple state DONE with SimpleActionClient in NS /amigo/head_ref/action_server
[ERROR] [1499529116.102728]: SimpleActionClient received DONE twice
[INFO] [1499529122.115004]: State machine terminating 'EXECUTE_PLAN':'succeeded':'arrived'
[INFO] [1499529122.115163]: State machine transitioning 'NAVIGATE':'arrived'-->'STOP_ANALYSIS_SUCCEED'
[INFO] [1499529122.185602]: State machine terminating 'STOP_ANALYSIS_SUCCEED':'done':'arrived'
[INFO] [1499529122.186143]: ' But I failed to follow you  I performed 2 tasks so far, still going strong!'

**Comment by MaxBaeten** [comment]
ATTEMPT 2. Still not working.
Operator is standing still for 9.617235 seconds
I'm close enough to the operator and he's been standing there for long enough
Checking if we pass the start timeout
Passed
[ERROR] [1499531481.541163]: Exception in your execute callback: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/server.py", line 64, in _add_action_cb
    action_result = self._task_manager.execute_next_action()
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/task_manager.py", line 52, in execute_next_action
    result = self._action_sequence.pop(0).start()
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/actions/action.py", line 82, in start
    self._start()
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/actions/follow.py", line 101, in _start
    self._execute_result.message += " I successfully followed {} ".format(self._goal.id)
AttributeError: 'NoneType' object has no attribute 'id'


[INFO] [1499531481.577721]: 'Moving to the meeting point.'
