### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/action_server#65]
[INFO] [1508169996.445736]: Robot heard 'perform a demonstration and take it to the flight_case' {u'actions': [{u'action': u'demo-presentation'}, {u'action': u'bring', u'object': {u'type': u'reference'}, u'target-location': {u'id': u'flight_case'}}]}
[INFO] [1508169996.446165]: 'I heard perform a demonstration and take it to the flight case, is this correct?'
[INFO] [1508170002.917070]: Question: , grammar: T -> yes | no
[INFO] [1508170002.917502]: Example: 'no'
[INFO] [1508170008.023862]: Robot heard 'yes' None
[INFO] [1508170008.028265]: Configuring action DemoPresentation with semantics {'action': 'demo-presentation'} and knowledge {}.
[WARN] [1508170009.238230]: Service 'robocup_recorder_toggle' unavailable, unable to start recording.
[INFO] [1508170009.238738]: Resulting knowledge = {}
[INFO] [1508170009.239430]: Configuring action Bring with semantics {'action': 'bring', 'object': {'type': 'reference'}, 'target-location': {'id': 'flight_case'}} and knowledge {}.
[INFO] [1508170009.239699]: No source given, trying to find at default location.
[ERROR] [1508170009.242565]: Exception in your execute callback: None
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/server.py", line 36, in _add_action_cb
    configuration_result = self._task_manager.set_up_state_machine(recipe['actions'])
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/task_manager.py", line 42, in set_up_state_machine
    configuration_result = action.configure(self._robot, config_data)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/actions/action.py", line 97, in configure
    self._configure(robot, config)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/src/action_server/actions/bring.py", line 77, in _configure
    expected_object_location = self._knowledge.get_object_category_location(category)[0]
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/robocup_knowledge/src/robocup_knowledge/environments/robotics_testlabs/common.py", line 223, in get_object_category_location
    location = category_locations[obj_cat].keys()[0]
KeyError: None

**Comment by rokusottervanger** [comment]
I will close this, as it will not happen again during a demo. I'll open another issue because the bring action is not robust for this input.
